spring.application.name=zkoos-demo1

# ZK
zk.homepage=customer-list

# Datasource (H2 in-memory)
spring.datasource.url=jdbc:h2:mem:zkoosdemo;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
